// Generated by @wagmi/cli@1.3.0 on 12.8.2023 at 13:59:47

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// CheckMade.sol
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const checkMadeSolABI = [
  { stateMutability: 'nonpayable', type: 'constructor', inputs: [] },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_from',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: '_hash',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
    ],
    name: 'CheckCreated',
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_hash', internalType: 'bytes32', type: 'bytes32' },
      { name: '_url', internalType: 'string', type: 'string' },
    ],
    name: 'addContentUrlToCheck',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_hash', internalType: 'bytes32', type: 'bytes32' },
      { name: '_description', internalType: 'string', type: 'string' },
    ],
    name: 'addDescriptionToCheck',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_hash', internalType: 'bytes32', type: 'bytes32' },
      {
        name: '_referenceHashes',
        internalType: 'bytes32[]',
        type: 'bytes32[]',
      },
    ],
    name: 'addReferenceHashesToCheck',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_hash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'createCheck',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_hash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'url', internalType: 'string', type: 'string' },
      { name: 'description', internalType: 'string', type: 'string' },
      { name: 'referenceHashes', internalType: 'bytes32[]', type: 'bytes32[]' },
    ],
    name: 'createCheckWithMetaData',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_hash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getContentUrlForCheck',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_hash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getDescriptionForCheck',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_hash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getMetaDataForCheck',
    outputs: [
      {
        name: '',
        internalType: 'struct CheckMade.CheckMetaData',
        type: 'tuple',
        components: [
          { name: 'contentUrl', internalType: 'string', type: 'string' },
          { name: 'description', internalType: 'string', type: 'string' },
          {
            name: 'referenceHashes',
            internalType: 'bytes32[]',
            type: 'bytes32[]',
          },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_hash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getReferenceHashesForCheck',
    outputs: [{ name: '', internalType: 'bytes32[]', type: 'bytes32[]' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '_hash', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getSignerAddressForCheck',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'pure',
    type: 'function',
    inputs: [{ name: '_content', internalType: 'bytes', type: 'bytes' }],
    name: 'hashBytes',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'pure',
    type: 'function',
    inputs: [{ name: '_content', internalType: 'string', type: 'string' }],
    name: 'hashString',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    name: 'hashToAddress',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    name: 'hashToCheckMetaData',
    outputs: [
      { name: 'contentUrl', internalType: 'string', type: 'string' },
      { name: 'description', internalType: 'string', type: 'string' },
    ],
  },
] as const
